### ISSUE TITLE
Option to calculate monthly holiday allowance

### ISSUE THREAD

**Issue by raspu** [stevermeister/dutch-tax-income-calculator#12]
Would it be possible to add an option to calculate the holiday allowance as a monthly payment instead of a yearly? I am not really sure if there's a tax difference, tho...

**Comment by stevermeister** [comment]
@raspu could you please tell me the difference?

**Comment by raspu** [comment]
Well, companies in the Netherlands sometimes offer the possibility to pay the holiday allowance in monthly installments instead of once a year.  It would be nice to see how your monthly net salary changes when they pay it this way.

**Comment by stevermeister** [comment]
oh, I see what you mean. 
this feature is already there, but works vice-versa:
you can select a checkbox here:
![Screenshot 2023-11-14 at 13 19 02](https://github.com/stevermeister/dutch-tax-income-calculator/assets/1526680/655c5639-3ec7-4fd4-9c3a-ec28906b5ba7)
it would mean that you have a holiday allowance, and it's already included into your gross income - and monthly net salary calculations you would get exactly as you want. 

only you need to take into account: if you have your gross salary amount in the contract not taking into account holiday allowance, you need to do the calculation yourself `gross * 1.08` and input it into the calculator. 
why it was not made in such a way in the first place? to make the calculation for you? - because there is no consistency in contracts here: some people have their holiday allowance included into their gross amount, and some - not

**Comment by raspu** [comment]
Clear! Thanks, Steve! I understood that the allowance is taxed differently than your regular salary, that's why I thought this option was needed.

Thanks for taking the time to explain it :).
