### ISSUE TITLE
Taxes values

### ISSUE THREAD

**Issue by drtdev1** [stevermeister/dutch-tax-income-calculator#16]
Hello,

How can we see what is the tax percentage applied to see how those numbers are calculated and which values have been applied?

Also, on my payslip I see an extra tax, "Zvw withholding employee". How is this addressed by your calculations/web application?

Thank you

**Comment by stevermeister** [comment]
1) from the right you can check all the checkboxes to have more information. 
2) it's open source, so you can check the code:
here you can find core logic on JS - https://github.com/stevermeister/dutch-tax-income-calculator-npm
and if you are more comfortable with Python - https://github.com/stevermeister/dutch-tax-income-calculator-python

also you can use CustomGPT - https://chat.openai.com/g/g-tOF7v2PcA-dutch-income-tax-calculator

> Zvw withholding employee

The "Zvw withholding for employees" refers to the health insurance contribution in the Netherlands under the Health Insurance Act (Zorgverzekeringswet, Zvw). It is a mandatory insurance premium withheld by the employer from the salary of the employees to cover part of the costs of the Dutch national healthcare system.

In the context of payroll calculations:
- This Zvw contribution is a type of payroll tax. Employers are responsible for withholding it from the gross salary and remitting it to the tax authorities.
- The rate for the Zvw withholding varies annually and depends on governmental decisions. As of recent years, it has been around a few percentage points of the income.

For the calculations provided in this Dutch Income Tax Calculator:
- The "Zvw withholding employee" specifically isn't outlined in the application. Instead, the payroll tax is calculated as a general category that may include the Zvw contribution if it were incorporated into the broader payroll tax definitions.
- Normally, this withholding would be part of the overall social security contributions which are covered by the "social tax" in the code. However, the specific code snippet provided only deals with a general social tax rate rather than breaking down individual components such as the Zvw.
