### ISSUE TITLE
Ruling with low income (like it was in previous version)

### ISSUE THREAD

**Issue by stevermeister** [stevermeister/dutch-tax-income-calculator#3]
> I see that the field for master's and under 30 is no longer in this new version, how do you adjust the lower income requirement for the 30% for this now?

**Comment by stockiller** [comment]
With the new version of the website, its not possible to specify what kind of 30% ruling someone is entitled to

https://user-images.githubusercontent.com/60266962/214048711-6c124e6d-ad1c-4b7e-948d-0757ed208317.png

Since the 30% ruling is only valid if the annual taxable salary is higher than ~41k , a person with master degree that has a lower salary, doesn't have the correct net value calculation because the annual taxable salary only needs to be higher than ~31k

**Comment by stevermeister** [comment]
@stockiller I've added the options that were in the old version, please check

<img width="372" alt="Screenshot 2023-02-18 at 18 13 47" src="https://user-images.githubusercontent.com/1526680/219879095-acdfda7f-78a6-489a-8730-5902c9cbced8.png">

**Comment by stockiller** [comment]
It works, thanks!
